### ISSUE TITLE
live consumptions preview

### ISSUE THREAD

**Issue by bosshog** [innowatio/iwwa-front#1]
as an energy manager, I want to preview the information of the widgets located on the dashboard so to avoid accessing the single widgets in case I want a quick overview
## Acceptance criteria
1. I go on the dashboard
2. I see the preview of the widgets

**Comment by fmondora** [comment]
As an Energy Manager I want to see the live consumption data for the points I have selected entering the widget and choosing the points among all the ones reported in the point list organised in hierarchical order (the points referring to a single "instance" are grouped together, e.g. multiple points in a store), so that I can have an overlook of the live consumptions and I can select the "father point" and have the preview of the cumulative (sum) data of the consumptions of all its children.

## Acceptance criteria
1. A logged in Energy Manager goes on the main page
2. A set of widget displays including the live consumption widget if this widget has been set to be on the main page
3. The user enters in the live consumption widget and select the points to be shown on the preview
4. The user select the "father" of a point group and the preview shows the sum of the consumptions of its children
5. The situation is critical and the live consumption widget is highlighting the threshold violation for the particular point
6. The user drills down to see detailed info about the event: event timing and duration, point name, point location, cost of the event

**Comment by bosshog** [comment]
Come Energy Manager voglio vedere i consumi in diretta per i punti che ho selezionato entrando nel widget e scegliendo dalla lista, organizzata in modo gerarchico rispettando la gerarchia riportata nel record (punti che si riferiscono ad uno stesso sito sono raggruppati ad albero - tipo file tree, es. punti di uno stesso centro commerciale), così da avere una panoramica dei consumi in diretta e posso selezionare un punto "padre" e ottenere l'anteprima del consumo cumulato (come somma) di tutti i punti figli.

## Acceptance criteria
1. Un Energy Manager accede al sistema e va alla pagina principale.
2. Un set di widget viene mostrato, con widget che possono avere dimensioni diverse, compreso il live consumption widget se questo è stato selezionato per stare nella home.
3. L'utente entra nel live consumption widget e seleziona al massimo 5 punti da mostrare nell'anteprima, anche appartenenti a siti diversi.
4. L'utente torna nella pagina principale e l'anteprima mostra i dati di consumo dei punti selezionati, con indicazione del nome e della tipologia dei punti.
5. L'utente entra nel live consumption widget e seleziona un punto "padre" (nel paragone con il file tree, come se selezionasse una cartella).
6. L'utente torna nella pagina principale e l'anteprima mostra il consumo cumulato dei punti "figli", con indicazione del nome e della tipologia del punto "padre".
7. La situazione è critica e il widget evidenzia il superamento della soglia per il punto corrispondente.
8. L'utente seleziona il punto critico per vedere i dettagli dell'evento: tempo e durata, nome del punto, localizzazione del punto, costo dell'evento, con possibilità di selezionare link che rimandino alla pagina dei consigli sull'utilizzo di energia.
9. Il punto non consuma energia e l'indicatore corrispondente evidenzia la situazione particolare.
